### ISSUE TITLE
Support Serverless Framework >= 2.0.0 

### ISSUE THREAD

**Issue by joker-8989** [dougmoscrop/serverless-plugin-split-stacks#132]
With the release of serverless version 2, this plugin now raises the following warning.

```
warning " > serverless-plugin-split-stacks@1.9.3" has incorrect peer dependency "serverless@1".
```

This plugin should update this dependency if there are no significant issues with Serverless 2 usage.
Currently this plugin works with version 2 of my environment.

**Comment by jamesallardice** [comment]
I have also been running this successfully on Serverless 2.x. The peer dependency on `serverless` was removed some time ago - a new version has not been published to npm since that commit went in. @dougmoscrop - if you can get an update published to npm it will resolve this warning without any further changes.

**Comment by dougmoscrop** [comment]
Thanks, will do!

**Comment by tonivdv** [comment]
@dougmoscrop Need any help with this?

**Comment by dougmoscrop** [comment]
Done as 1.10 - sorry I took so long :(

**Comment by tonivdv** [comment]
> sorry I took so long :(

No need to apologise. It's great you made this plugin and spend your free time on this. All we can say is a big thank you! Cheers
