### ISSUE TITLE
Npm version is mentioned as 1.9.3 but the code differs from the latest available on git repo

### ISSUE THREAD

**Issue by kunalchoudhary31** [dougmoscrop/serverless-plugin-split-stacks#147]
Hello @dougmoscrop 

The code available at here on git is handling the 500 resources limit error. 
But the code we install using npm package manager is outdated.

Can you please make these two sync. I really appreciate your efforts for writing this plugin.

**Comment by mnickkk** [comment]
@kunalchoudhary31 the code differs, because master is not the release version (look at Tags):
![image](https://user-images.githubusercontent.com/7702564/102596150-0f343680-4119-11eb-9679-af8491f5a74d.png)

bear in mind that the master rises the limit, but also creates other issues due to these changes:
https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/master/lib/utils.js#L243
https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/master/lib/utils.js#L248

you can always fork this repo, branch of the tag version and increase the stack limit yourself, then point to that repo/branch in your package.json

**Comment by kunalchoudhary31** [comment]
@mnickkk  thankyou . i did as what you said and it worked. Highly appreciate it.
