### ISSUE TITLE
Maximum policy size error

### ISSUE THREAD

**Issue by lithin** [dougmoscrop/serverless-plugin-split-stacks#25]
Deploying a sizeable serverless application, we had first hit the cap of 200 resources. This plugin solved that issue but possibly introduced another one later on:

`An error occurred: IamRoleLambdaExecution - Maximum policy size of 10240 bytes exceeded for role beekeeper-serverless-staging-eu-west-1-lambdaRole.`

![screen shot 2018-01-26 at 11 22 39](https://user-images.githubusercontent.com/6726858/35437639-437e34a6-028b-11e8-8f0c-0697bd157d81.png)

It's an issue already reported with core https://github.com/serverless/serverless/issues/2508 but looking at `.serverless`, I'm wondering if it's not the way we split the stacks that does this. I assume that the definition of permissions is in `.serverless/cloudformation-template-Permissions-nested-stack.json` which is very verbose and is 37KB in our project (which is 27KB over the aws threshold).

Do you have any recommendations on what to do when we hit this issue?

**Comment by dougmoscrop** [comment]
I don't think the issue is the splitting per se, but that you have too many permissions in your iamRoleStatements.

My colleague happens to have just written a plug-in for this issue ! 

Check out: serverless-plugin-custom-roles 

You will have some work to do come up with individual function roles and refactor your policy statements.

Example is we do a thing where we make a statement for "SqsRead" and only include it to the two or so functions that need sqs access. 

This is better from a security perspective too (each function only has access to what it needs) but it becomes a necessity with too many global perms

**Comment by lithin** [comment]
Thank you for a quick reply :) I dug a bit more into the details and realised that it's mainly the logs permissions that are part of core serverless and will need to take it from there.

**Comment by craig-dae** [comment]
I'm having this issue now. 

I already have `serverless-iam-roles-per-function` in my project. I don't know how easy it would be to switch to `serverless-plugin-custom-roles`, but I don't think I can use both.
