### ISSUE TITLE
Resources Count

### ISSUE THREAD

**Issue by mataide** [dougmoscrop/serverless-plugin-split-stacks#30]
Can you explain about how count works?
```

Serverless: [serverless-plugin-split-stacks]: Summary: 120 resources migrated in to 3 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 190
Serverless: [serverless-plugin-split-stacks]:    - APINestedStack: 56
Serverless: [serverless-plugin-split-stacks]:    - PermissionsNestedStack: 30
Serverless: [serverless-plugin-split-stacks]:    - VersionsNestedStack: 34
```

Summary: 120 resources: Shouldnt this number be the total of all resources?
- (root): 190: Is this number the total?

I really dont understand these numbers.

**Comment by dougmoscrop** [comment]
120 is the number of resources that were moved in to new stacks (56 + 30 + 34).

190 is how many resources remain in the original stack also including the nested stacks (which themselves are 1 resource each). It's just meant to show how close you are to the limit.

They're mostly just debug info that I left in from when I was validating that the plugin was doing stuff. Do you have some information that you need that isn't there, or any suggetions for how to clarify?

**Comment by mataide** [comment]
So, my total resources without the plugin should be 307?

And if my total is 190, I am in danger again, do you know if it is possible to ask AWS to improve the limit?

**Comment by dougmoscrop** [comment]
That's right, 307 + 3 "overhead" from the splitting.

As far as I know, the 200 is a hard limit in CF.

This plugin takes a conservative approach to migrating resources. You can customize how they are migrated - it's in the docs. First thing to do is look at your `./serverless/cloudformation-update-template.json` file and see what resources you have.

Just be warned that each time you change which resources are migrated, it can require downtime (you have to delete and recreate the stack), because CloudFormation doesn't handle moving resources from one stack to the other. (It just sees a delete and a create - which can create downtime of its own, or, from a race condition, try to create the resource before it has been deleted, and fail).

Another option is trying the fork: https://github.com/dougmoscrop/serverless-plugin-split-stacks/pull/14 -- just modify the package.json version to point to the github url (`github:medikoo/serverless-plugin-split-stacks#stack-per-lambda`

This method of splitting is what I originally wanted to do with the plugin, but I had problems and needed something that worked, hence 1.0 did not take this approach. The new approach is what I would like to see 2.0 be, but we need more people to test with different configurations.
